from __future__ import annotations

from pathlib import Path
from typing import Protocol, runtime_checkable, Any


@runtime_checkable
class TraceBackend(Protocol):
    """Common query contract used by every diagnostic skill.

    Backends may be a text systrace parser or Perfetto Trace Processor. Skills
    must depend on this contract instead of parsing a trace format directly.
    """

    source_path: str
    events: list[Any]
    slices: list[Any]
    states: dict[int, list[Any]]
    running: list[Any]
    thread_meta: dict[int, tuple[str, int]]
    blocked_reasons: dict[int, list[tuple[float, int, str]]]
    trace_start: float | None
    trace_end: float | None

    def find_slices(self, pattern=None, **kwargs): ...
    def longest(self, pattern: str, **kw): ...
    def first(self, pattern: str, **kw): ...
    def sum_slice_ms(self, pattern: str, **kw) -> float: ...
    def state_ms(self, tid: int, start: float, end: float): ...
    def state_ms_for_process(self,tgid:int,start:float,end:float): ...
    def intervals(self, tid: int, state: str, start: float, end: float): ...
    def process_intervals(self, tgid: int, state: str, start: float, end: float): ...
    def nested_slices(self, parent, pattern=None): ...
    def blocked_reason_near(self, tid: int, start: float, end: float): ...
    def event_time_latency_ms(self, tgid:int, start:float,end:float): ...
    def sum_paired_event_ms(self, begin_event: str, end_event: str, *, tgid=None, tid=None, start=None, end=None) -> float: ...
    def event_count(self, event_name: str) -> int: ...
    def has_event(self, event_name: str) -> bool: ...
    def find_events(self, names, *, start=None, end=None, tgid=None): ...
    def tids_for_process(self, tgid: int): ...
    def sum_interval_overlap_ms(self, left, right) -> float: ...
    def same_cpu_interval_overlap_ms(self, left, right) -> float: ...
    def running_occupants(self, intervals, cpus=(), exclude_tids=()): ...
    def summary_counts(self) -> dict[str, int]: ...
    def capabilities(self) -> dict[str, bool]: ...
    def close(self) -> None: ...


def is_atrace_container(path: str) -> bool:
    data = Path(path).read_bytes()[:8192]
    return b"TRACE:\n" in data or b"# tracer:" in data or b"tracing_mark_write:" in data
